### ISSUE TITLE
dependency `subsemble` not on CRAN

### ISSUE THREAD

**Issue by barryrowlingson** [Envirometrix/landmap#1]
Looks like `subsemble` version from 2014 was archived off CRAN in Jan 2019.

It does install from its git repo via `devtools::install_github("ledell/subsemble")`

Maybe note that in the readme until it appears on CRAN again.

landmap installs successfully once that dependency is got from github.

**Comment by thengl** [comment]
Thank you Barry. We might migrate all the ensemble functionality to the mlr package (just discussing with Patrick Schratz). Working on it.

**Comment by thengl** [comment]
Package is now based on mlr
